
remote_theme: pmarsceill/just-the-docs 
title: José Domingo
description: Enlaces, recursos, cursos, tutoriales, libros, ...
color_scheme: mitema

earch_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

# Aux links for the upper right navigation
aux_links:
  "Accede al repositorio en GitHub":
    - "//github.com/josedom24/josedom24.github.io"

# Back to top link
back_to_top: true
back_to_top_text: Inicio

footer_content: "Esta documentación tiene licencia <a href=\"https://github.com/josedom24/curso_docker_2022/blob/main/LICENSE\">GNU General Public License v2.0</a>"
